version: '3.7'
services:
    mysql:
        image: mysql:8.0
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

    php:
        container_name: php
        build:
            context: .
            dockerfile: docker/dev/php/Dockerfile
        user: '${LOCAL_USER}'
        volumes:
            - '.:/app'

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        depends_on:
            - php
        volumes:
            - './public/:/app/public:ro'
            - './docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PUBLIC_PORT}:80'
